### ISSUE TITLE
DIV: 16394Hz signals are not inverted towards each other

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#13]
On DIV sheet, it makes no sense that the local label 16394Hz has a bar on top and the hierarchical label with the same name does not. They are both inverted one time, one because of the ~Q output and the other because of the separate inverter UVYN. I would drop the local label and directly connect it to it's destination at MUX ULUR below, so we don't have to think about another name for that net.

**Comment by rgalland** [comment]
Local net name removed but I haven't changed the name to 16394 instead of 16384. I'll do it later as it implies that other clocks have to be changed to match GB_CLK/N.

**Comment by msinger** [comment]
Oh no. The 9 is just a typo of mine. 16384 is correct of course. My issue was just the inversion bar on top that indicated that the two were inverted towards each other, which was wrong. So it should be fixed now.
