### ISSUE TITLE
NOT_VRAM_MEM_RQ name suggestion

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#158]
On EXT_ADDR_BUSES sheet, there is a net called NOT_VRAM_MEM_RQ driven by TEXO. I think it would be less confusing if we change it to NON_VRAM_MEM_RQ. The word NOT should be equal to putting a bar ontop (/VRAM_MEM_RQ), hence making it low-active, which it isn't. I feel NON_VRAM describes better that it is a high-active MEM_RQ, but just for everything else than VRAM.

**Comment by rgalland** [comment]
Very good suggestion. I will modify the net name.

**Comment by msinger** [comment]
Oops. You wrote NONE instead of NON in three places.
