### ISSUE TITLE
MODE2 wire is mislabeled as MODE1

### ISSUE THREAD

**Issue by tclemens** [msinger/dmg-schematics#161]
It's source is `OAM_PARSING && !DMA_RUN`. It's also a component of `STAT[1]` which should only be set in modes 2 and 3.

**Comment by msinger** [comment]
Thank you, I think you are right. Seems like we have overlooked this. If it raises bit 1 of the MODE[1:0] field in the STAT register, then it must be high during MODE2, not MODE1. I will check simulation results once more just to make sure, and then fix it.

**Comment by msinger** [comment]
Hi @rgalland, thanks, I'm already done. Just about to push. :)

**Comment by rgalland** [comment]
@msinger , man! you were fast.

**Comment by msinger** [comment]
Let's hope I didn't miss something.

**Comment by msinger** [comment]
Changing INT_VBL_BUF to INT_VBL would clean up FF0F INT (page 10). This was bothering me for a while that this is the only interrupt that hat a _BUF in its name.

**Comment by msinger** [comment]
Oh, careful. :)
You mean, INT_HBL to MODE0.

**Comment by rgalland** [comment]
Yes, that's what I meant.
