### ISSUE TITLE
CLOCK: ASOL has swapped inputs and swapped outputs

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#18]
For NOR-latch ASOL on clock sheet, compared to furrtek/DMG-CPU-Inside#29 and [here](http://iceboy.a-singer.de/doc/dmg_cells.html#srlatch), the SET&RESET inputs are swapped and also the Q and ~Q outputs are swapped. Since both, inputs and outputs are swapped, this is logically still correct, though. But I think we should keep it consistent. Was this an accident or was there a reason. I can change the pinning in the documentation when necessary.

**Comment by rgalland** [comment]
![ASOL](https://user-images.githubusercontent.com/27197663/158580908-56223300-fd93-4013-be91-ac0420c7af09.png)

Isn't it what you see?

**Comment by msinger** [comment]
No, I see this:
![nor-latch-ccw](https://user-images.githubusercontent.com/186443/158587553-722033be-c6e6-45d8-8d31-9092ccd916e4.png)
The ASOL label already correctly indicates how the cell is rotated. All cells in this row are rotated 90° counter-clockwise compared to the usual vertical columns of cells. It also must be flipped, because the supply rails are flipped for this row.

I understand you did this:
![nor-latch-cw](https://user-images.githubusercontent.com/186443/158587957-64a028f4-f245-4c08-8f63-d1d18e684e3a.png)
But then the knobs in the middle don't match, so it can't be rotated clockwise.

**Comment by rgalland** [comment]
Incredible. Yes, I think you are right. I'll change is now.
