### ISSUE TITLE
SER: SCK IO-pad is not connected correctly

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#27]
On serial sheet, the SCK IO pad is not correctly connected:

* First, it should be IOBUF_C, not _B. SCK is the only IO of that type. I don't know what's the difference, though,
* DRV_LOW and DRV_HIGH inputs are swapped. NOR gate KUJO should be connected to the NMOS driver (DRV_LOW) and NAND gate KEXU should be connected to the PMOS driver (DRV_HIGH).
* The pull-up resistor should be enabled by signal SCK_DIR, instead of GND.

**Comment by rgalland** [comment]
Well done for working this one out.
