### ISSUE TITLE
APU_DEC: Inputs of some gates are swapped

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#46]
On APU decode sheet, the inputs of following gates are swapped:
DYVA, CAXE, EDAF, DECO, DUJA, COVY, DUTU, DARA, DOZA, EMOR, EKEZ

I compared it with the die shot. Furrtek also made a few mistakes here.

**Comment by msinger** [comment]
Just noticed, the inputs of the NAND_4 gates are also scrambled up. I say we leave them like that for now. :)

**Comment by rgalland** [comment]
I'll leave a note on the schematics about the NAND inputs.
