### ISSUE TITLE
APU_DEC: Proposal to move DOXY

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#47]
On APU decode sheet, I think it is better if DOXY is moved directly behind EKAG to the right. Then the structure is the same for all these decoders. When moved, it needs to be flipped, so that input 1 is at the bottom, getting in label FF2X. The label XXX6 can then be dropped.

**Comment by rgalland** [comment]
Good suggestion. For some reason I missed this issue in my last commit.
