### ISSUE TITLE
APU_CH1: GEXU is NAND latch

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#57]
On APU CH1 sheet, GEXU should be a NAND latch, not an AND gate. FEMY goes into GEXUs ~RESET input, GEPU into its ~SET input. ~Q output is CH1_FEN, Q is not connected.

**Comment by rgalland** [comment]
Well spotted. This error will be on other sheets as similar mechanism is used and ch2 and ch4 at least.

**Comment by msinger** [comment]
You used wrong output.

**Comment by rgalland** [comment]
Yes, indeed. I will be added to next commit with identical change in CH2 and CH4.
