### ISSUE TITLE
APU_CH1: Input of KURY is wrong

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#59]
On APU CH1 sheet, the input of inverter KURY should come from KOZY, not KEZU/CH1_EG_STOP.

**Comment by rgalland** [comment]
I won't close this issue as I reworked this area. Can you please cast an eye on it and also check the area around FYTE. It should be a bit neater.

**Comment by rgalland** [comment]
Same mistakes on CH2 including the NAND latch. I''ll fix them as part of this issue.

**Comment by msinger** [comment]
I approve :)
