### ISSUE TITLE
APU CH3 REGS: Missing FEVO and wrong connections to GUXE

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#63]
On APU CH3 register sheet, FEVO is missing. Also there are wrong connections carried over from Furrtek.

* Q output of GUXE should be connected to FEVO's input and nowhere else. Then output of FEVO goes into GEKO, like it is drawn in Furrtek's schematics.
* ~Q output of GUXE should go into FUVO input 1. The label ~CH3_AMP_EN (aka. ~FF1A_D7) should stay at the ~Q output.

**Comment by msinger** [comment]
Also look at #64 before making changes. It's in the same area.

**Comment by rgalland** [comment]
Also fixed BUTA on CH2 as output was not connected to ~Q. I also renamed all labels to CHx_FDIS instead of CHx_FEN as it makes more sense.
