### ISSUE TITLE
APU CH4: EROX uses wrong output

### ISSUE THREAD

**Issue by msinger** [msinger/dmg-schematics#73]
On APU channel 4 sheet, EROX should use Q output instead of ~Q.

**Comment by msinger** [comment]
I know, this is contradicts CH1 and CH2. I don't understand it either.

**Comment by rgalland** [comment]
This doesn't make sense.

**Comment by rgalland** [comment]
Output Q should be used for all 3 channels. Upon reset or channel restart, the envelope out clocking is re-enabled.

**Comment by msinger** [comment]
Maybe we got something else wrong in these areas.
