### ISSUE TITLE
Redrawing FULL ADD symbol

### ISSUE THREAD

**Issue by rgalland** [msinger/dmg-schematics#81]
Do you mind if we draw the FULL ADD symbol to have from top to bottom : 
- A, B, CIN on the left
- and COUT and SUM on the right?

This will prevent a lot of lines crossing over. At the moment, only the SWEEP sheet is affected but it look as I always try to have the MSB at the top.

**Comment by msinger** [comment]
Let's do it. It's good to have everything ordered the same way. And if changing the pin order is making everything more readable, then that's good to.
